name: Update Notion Release Notes

on:
  release:
    types: [published]

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Release Info
        id: release_notes
        run: |
          # Escape JSON special characters in release body
          ESCAPED_BODY=$(echo '${{ github.event.release.body }}' | jq -sR)

          # Create JSON payload file
          cat << EOF > payload.json
          {
            "parent": {
              "database_id": "${{ secrets.NOTION_DATABASE_ID }}"
            },
            "properties": {
              "Version": {
                "title": [{
                  "text": {
                    "content": "${{ github.event.release.tag_name }}"
                  }
                }]
              },
              "Release Date": {
                "date": {
                  "start": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
                }
              },
              "Changes": {
                "rich_text": [{
                  "text": {
                    "content": ${ESCAPED_BODY}
                  }
                }]
              },
              "GitHub Link": {
                "url": "${{ github.event.release.html_url }}"
              }
            }
          }
          EOF

      - name: Send Release Notes to Notion
        run: |
          curl -X POST "https://api.notion.com/v1/pages" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            -d @payload.json
